export default [ { "flightId": 711088298,
        "scheduledBlockMinutes": 135,
        "blockMinutes": 124,
        "scheduledAirMinutes": 115,
        "airMinutes": 109,
        "scheduledTaxiOutMinutes": 9,
        "taxiOutMinutes": 9,
        "scheduledTaxiInMinutes": 11,
        "taxiInMinutes": 6,
        "scheduledEquipmentIataCode": "73W",
        "actualEquipmentIataCode": "73R",
        "tailNumber": "N7743B" },
      { "flightId": 711080292,
        "scheduledBlockMinutes": 180,
        "blockMinutes": 186,
        "scheduledAirMinutes": 157,
        "airMinutes": 163,
        "scheduledTaxiOutMinutes": 12,
        "taxiOutMinutes": 22,
        "scheduledTaxiInMinutes": 11,
        "taxiInMinutes": 1,
        "scheduledEquipmentIataCode": "73W",
        "actualEquipmentIataCode": "73W",
        "tailNumber": "N478WN" },
      { "flightId": 711063199,
        "scheduledBlockMinutes": 144,
        "blockMinutes": 159,
        "scheduledAirMinutes": 115,
        "airMinutes": 117,
        "scheduledTaxiOutMinutes": 11,
        "taxiOutMinutes": 37,
        "scheduledTaxiInMinutes": 18,
        "taxiInMinutes": 5,
        "scheduledEquipmentIataCode": "ERJ",
        "actualEquipmentIataCode": "E45",
        "tailNumber": "N17115" } ]